config/routes.rb
Rails.application.routes.draw do

  resources :feeds do
    member do
      get 'fetch'
    end
    collection do
      get 'search'
      get 'fetch_all'
    end
  end

  resources :categories

  get 'clips/index'
  get 'clips/vis'
  get 'clips/create'
  delete 'clips/destroy'

  resources :entries do
    member do
      get 'toggle_summary'
    end
    collection do
      get 'search'
    end
  end

  root :to => 'entries#index'

end

app/models/feed.rb
class Feed < ActiveRecord::Base
  belongs_to :category
  has_many :entries, :dependent => :destroy
end

app/controllers/feeds_controller.rb
class FeedsController < ApplicationController

  require 'feedjira'
  before_action :set_feed, :only => [:show, :edit, :update, :destroy, :fetch] 
  before_action :set_categories, :only => [:index, :show, :new, :edit] 

  def feed_params
    params.require(:feed).permit(:category_id, :title, :url, :feed_url, :last_modified)
  end

  # GET /feeds
  # GET /feeds.json
  def index
    @entries = Entry.includes(:clip).all
    @feeds = Feed.all
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @feeds }
    end
  end

  # GET /feeds/1
  # GET /feeds/1.json
  def show
    @entries = Entry.where(:feed_id => params[:id]).page(params[:page])
    respond_to do |format|
      format.html # show.html.erb
      format.json {
        render :json => {
                   :feed     => @feed,
                   :category => @category,
                   :entries  => @entries
               }
      }
    end
  end

  # GET /feeds/new
  # GET /feeds/new.json
  def new
    @feed = Feed.new
  end

  # GET /feeds/1/edit
  def edit
  end

  # POST /feeds
  # POST /feeds.json
  def create
    @feed = Feed.new(feed_params)
    respond_to do |format|
      if @feed.save
        format.html { redirect_to @feed, notice: 'Feed was successfully created.' }
        format.json { render json: @feed, status: :created, location: @feed }
      else
        format.html { render action: "new" }
        format.json { render json: @feed.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /feeds/1
  # PUT /feeds/1.json
  def update
    #@feed = Feed.find(params[:id])
    respond_to do |format|
      if @feed.update(feed_params)
        format.html { redirect_to @feed, notice: 'Feed was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @feed.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /feeds/1
  # DELETE /feeds/1.json
  def destroy
    @feed.destroy
    respond_to do |format|
      format.html { redirect_to feeds_path }
      format.json { head :no_content }
    end
  end

  def fetch_all

    Feed.all.each do |feed|

      p 'Fetching feed from ' + feed.title
      parsedFeed = Feedjira::Feed.fetch_and_parse feed.feed_url
      flag = true

      # Update feed meta data
      feed.title = parsedFeed.title
      feed.last_modified = parsedFeed.last_modified
      if parsedFeed.url then feed.url = parsedFeed.url end
      feed.save
      
      # Save entries
      parsedFeed.entries.reverse.each do |feed_entry|

        if !Entry.where(:url => feed_entry.url).exists?
          p 'Add => ' + feed_entry.url

          entry = Entry.new({
                              :title        => feed_entry.title,
                              :url          => feed_entry.url,
                              :summary      => (feed_entry.summary || feed_entry.content || '').gsub(/<.+?>/m, ''),#.slice(0, 255),
                              #:published_at => Time.parse(feed_entry.published.to_s),
                              :published_at => feed_entry.published.to_s,
                              :feed_id      => feed.id
                            })
          entry.save
        end
      end
      
    end

    Entry.destroy_overflowed_entries
    
    @feeds = Feed.all
    redirect_to entries_path
  end

  def fetch

    #options = {
      #user_agent: USER_AGENT, 
      #if_modified_since: @feed.last_fetched, 
      #timeout: 30, 
      #max_redirects: 2,
      #compress: true
    #}

    p 'Fetching feed from ' + @feed.title.to_s
    parsedFeed = Feedjira::Feed.fetch_and_parse @feed.feed_url
    #new_entries = Feedjira::Feed.update_from_feed parsedFeed
    #p parsedFeed.new_entries

    flag = true

    p 'Updated entries exist? ' + flag.to_s

    # Update feed meta data
    @feed.title = parsedFeed.title
    @feed.last_modified = parsedFeed.last_modified
    if parsedFeed.url then @feed.url = parsedFeed.url end
    @feed.save

    # Save entries
    parsedFeed.entries.reverse.each do |feed_entry|

      if !Entry.where(:url => feed_entry.url).exists?
        p 'Add => ' + feed_entry.url
        entry = Entry.new({
                            :title        => feed_entry.title,
                            :url          => feed_entry.url,
                            :summary      => (feed_entry.summary || feed_entry.content || '').gsub(/<.+?>/m, ''),#.slice(0, 255),
                            #:published_at => Time.parse(feed_entry.published.to_s),
                            :published_at => feed_entry.published.to_s,
                            :feed_id      => @feed.id
                          })
        entry.save
      end
    end
    
   Entry.destroy_overflowed_entries(@feed.id)
   
    #@feeds = Feed.all
    redirect_to feed_path
  end

 
  private

  def set_feed
    @feed = Feed.find(params[:id])
  end

  def set_categories
    @categories = Category.order(:name)
    #@categories = Category.all
  end
  
end

app/helpers/feeds_helper.rb
module FeedsHelper
end

app/views/feeds/_form.html.erb
<%= form_for(@feed) do |f| %>
  <% if @feed.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@feed.errors.count, "error") %> prohibited this feed from being saved:</h2>

      <ul>
      <% @feed.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

    <div class="field">
      <%= f.label :feed_url %><br />
      <%= f.text_field :feed_url %>
    </div>

    <div class="field">
      <%= f.label :category_id %><br />
      <%= f.collection_select :category_id, @categories, :id, :name, :prompt => "選択してください" %>
    </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/feeds/edit.html.erb
<% content_for :main do %>

    <div align="center">
      <h1>Editing feed</h1>

      <%= render 'form' %>

      <%= link_to 'Show', @feed %> |
      <%= link_to 'Back', feeds_path %>
    </div>
<% end %>

app/views/feeds/index.html.erb
<% content_for :main do %>

	<div align="center">
		<h1>Feeds</h1>

		<%# link_to 'Entries', entries_path %>
		<%= link_to 'Fetch All Feed', fetch_all_feeds_path %>
		<%= link_to 'New Feed', new_feed_path %>

		<table>
			<tr>
				<th></th>
				<th>Category</th>
				<th>Title</th>
				<th>Number of entries</th>
				<th></th>
				<th></th>
				<th></th>
				<th></th>
			</tr>

			<% @feeds.each do |feed| %>
				<tr style="background-color:<%= cycle('#FFffFF', '#FFggFF') %>">
					<td><%= feed.id %></td>
					<td><%= if feed.category then feed.category.name else "" end %></td>
					<td><%= link_to feed.title, feed %></td>
					<th><%= feed.entries.count %></th>
					<td><%= link_to 'Edit', edit_feed_path(feed) %></td>
					<td><%= link_to 'Fetch', fetch_feed_path(feed) %></td>
					<td><%= link_to 'Destroy', feed, confirm: 'Are you sure?', method: :delete %></td>
					<td><%= link_to 'Web Site', feed.url, :target => ["_blank"] %></td>				</tr>
			<% end %>

			<tr>
				<th>Total</th>
				<th></th>
				<th></th>
				<th><%= @entries.count %></th>
				<th></th>
				<th></th>
				<th></th>
				<th></th>
			</tr>
		</table>
	</div>

<% end %>

app/views/feeds/new.html.erb
<% content_for :main do %>
	<div align="center">
		<h1>New feed</h1>

		<%= render 'form' %>

		<%= link_to 'Back', feeds_path %>
	</div>
<% end %>

app/views/feeds/show.html.erb
<% content_for :main do %>
	<div align="center">
		<p id="notice"><%# notice %></p>
		<p>
			<b>Title:</b>
			<%= @feed.title %>
		</p>
		<p>
			<b>Url:</b>
			<%= link_to @feed.url, @feed.url, :target=>["_blank"] %>
		</p>
		<p>
			<b>Feed Url:</b>
			<%= @feed.feed_url %>
		</p>
		<p>
			<b>Category:</b>
			<% if @feed.category %>
				<%= link_to @feed.category.name, @feed.category %>
			<% else %>
				Yet Categorised
			<%end %>
		</p>

		<%= link_to 'Fetch', fetch_feed_path(@feed) %> |
		<%= link_to 'Edit', edit_feed_path(@feed) %>
	</div>
	<%= render 'shared/entries' %>

<% end %>