config/routes.rb
Rails.application.routes.draw do

  resources :feeds do
    member do
      get 'fetch'
    end
    collection do
      get 'search'
      get 'fetch_all'
    end
  end

  resources :categories

  get 'clips/index'
  get 'clips/vis'
  get 'clips/create'
  delete 'clips/destroy'

  resources :entries do
    member do
      get 'toggle_summary'
    end
    collection do
      get 'search'
    end
  end

  root :to => 'entries#index'

end

app/models/entry.rb
# coding: utf-8
class Entry < ActiveRecord::Base
  belongs_to :feed
  has_one :clip, :dependent => :destroy

  MAX_NUMBER_OF_ENTRIES_PER_FEED = 50
  require 'natto'
  
  # kaminari
  default_scope { order(published_at: :desc) }
  #default_scope { order('RANDOM()') }
  #paginates_per 50
  
  def self.destroy_overflowed_entries(*feed_id)
    clipped_entries = Clip.pluck(:entry_id)
    if feed_id
      p "AAAAAAAAAAAAAAA"
      entries = Entry.where(:feed_id => feed_id).pluck(:id)
      entries = entries - clipped_entries
      if entries.length > MAX_NUMBER_OF_ENTRIES_PER_FEED
        entries = entries.reverse[0..(MAX_NUMBER_OF_ENTRIES_PER_FEED-1)]
        entries.reverse!
        p "Destroy entries from a feed"
        Entry.destroy_all(:id => entries)
      end
    else
      Feed.all.each do |feed|
        entries = Entry.where(:feed_id => feed.id).pluck(:id)
        entries = entries - clipped_entries
        if entries.length > MAX_NUMBER_OF_ENTRIES_PER_FEED
          entries = entries.reverse[0..(MAX_NUMBER_OF_ENTRIES_PER_FEED-1)]
          entries.reverse!
          p "Destroy entries from feed #{feed.title}"
          Entry.destroy_all(:id => entries)
        end
      end
    end
  end

  #クラスメソッドseach
  def self.search(search)
    if search
      Entry.where(['title LIKE ? or summary LIKE ?', "%#{search}%", "%#{search}%"])
    else
      Entry.all
    end
  end
  
  def self.word_count(entries)

    titles = ""
    texts = ""
    entries.each do |entry|
      titles += entry.title
      texts += entry.summary
    end
    texts += titles # とりあえず

    word_array = Array.new
    nm = Natto::MeCab.new
    #regex = /^名詞/
    regex = /^名詞,固有名詞/
    nm.parse(texts) do |node| # 名詞だけword_arrayへ
      if node.feature =~ regex #.force_encoding("UTF-8")
        word_array << node.surface #.force_encoding("UTF-8")
      end
    end

    tmp = nm.parse(texts)
    p tmp

    # word_hash: {["word" => count],...}
    word_hash = Hash.new
    word_array.each do |key|
      word_hash[key] ||= 0
      word_hash[key] += 1
    end
    
    regex_white = /[一-龠]+|[ぁ-ん]+|[ァ-ヴー]+|[a-zA-Z]+|[ａ-ｚＡ-Ｚ]+/ # white list
    #regex_black = Regexp.new(/[!-¥:-@≠\[-`{-~\]]/) # black list
    #word_hash.delete_if{|k, v| k =~ regex_black by black list
    word_hash = word_hash.select{|k, v| k =~ regex_white}.to_h # filtering by white list

    word_hash = word_hash.sort_by {|k, v| v}.to_h # sort by word count
    
    words_total = word_hash.values.inject(0){|sum, i| sum+i}
    #p words_total
    word_hash_normalized = word_hash.map {|k, v| [k, v.quo(words_total).to_f]}.to_h
    #p word_hash
    #p word_hash_normalized
    #return word_hash.to_a
    return word_hash_normalized.to_a

    #nm.parse(texts) do |n|
      #puts "#{n.surface}\t#{n.feature}"
      #words.push(n.surface if n.)
    #end
  end

end

app/controllers/entries_controller.rb
class EntriesController < ApplicationController

  before_action :set_clipped_entries, :only => :clipped
  before_action :set_category, :only => [:show, :edit, :update, :destroy]
  before_action :set_categories, :only => [:index, :show, :search, :edit, :update, :destroy]

  def entry_params
    params.require(:entry).permit(:feed_id, :summary, :title, :url, :published_at)
  end

  # GET /entries
  # GET /entries.json
  def index
    #@categories = Category.includes(:feeds).all
    #@feeds = Feed.all
    #@entries = Entry.includes(:clip).page(params[:page])
    @entries = Entry.includes(:clip).page(params[:page])
   respond_to do |format|
      format.html # index.html.erb
      format.json {
        render :json => {
                   :feed     => @feed,
                   :category => @category,
                   :entries  => @entries
               }
      }
    end
  end

  # GET /entries/1
  # GET /entries/1.json
  def show
    @entry = Entry.includes(:feed, :clip).find(params[:id])
    respond_to do |format|
      format.html # show.html.erb
      format.json {
        render :json => {
                   :feed     => @feed,
                   :category => @category,
                   :entries  => @entry
               }
      }
    end
  end
  
  def search
    @feed = Feed.all
    @word = params[:search]
    @entries = Entry.search(@word).page(params[:page])
    respond_to do |format|
      format.html # show.html.erb
      format.json {
        render :json => {
                   :feed     => @feed,
                   :category => @category,
                   :entries  => @entries
               }
      }
    end
  end

  def toggle_summary
    p params[:id]
    @entry = Entry.find(params[:id])
    #@e_id = params[:id]
  end
  
  private
  
  def set_category
    @category = Category.find(params[:id])
  end

  def set_categories
    @categories = Category.order(:name)
  end

  def set_clipped_entries
    clipped_entries_id = Clip.pluck(:entry_id)
    @entries = Entry.where(:id => clipped_entries_id).page(params[:page])    
  end

end

app/helpers/entries_helper.rb
module EntriesHelper
end

app/views/entries/clipped.html.erb
<% content_for :main do %>
    <%= include_gon %>
    <%= javascript_include_tag "d3/d3.min.js" %>
    <%= javascript_include_tag "d3/d3.layout.cloud.js" %>

<h1>Clipped Entries</h1>

    <%= link_to 'All Entries', entries_path %>
    <%= link_to 'Feeds', feeds_path %>
    <%= link_to 'Categories', categories_path %>

    <br />

    <div id="word_cloud"></div>

    <%= render 'shared/entries' %>
	
	<script type="text/javascript">
	//word_cloud();
	</script>

<% end %>

app/views/entries/index.html.erb
<% content_for :main do %>

	<div align=center>
		<h1>All Entries</h1>

		<div id="menu-tree">
			<%= form_tag search_entries_path, :method => 'get' do %>
				<p>
					<%= text_field_tag :search, params[:search] %>
					<%= submit_tag "Search", :title => nil %>
				</p>
			<% end %>
			<span>
				<i class="fa fa-paperclip"></i>
			</span>
			&nbsp
			<%= link_to 'Clipped Entries', clips_index_path %>
			&nbsp&nbsp
			<span>
				<i class="fa fa-rss"></i>
			</span>
			&nbsp
			<%= link_to 'Fetch All Feed', fetch_all_feeds_path %>
			<br />
			<span id="menu-tree-t">
				<i class="fa fa-chevron-down"></i>
			</span>
			&nbsp
			<%= link_to "Categories", categories_path %>
			&nbsp-&nbsp
			<%= link_to "Feeds", feeds_path %>
			<div id="categories">
				<ul>
					<% @categories.each do |category| %>
						<li>
							<%= link_to category.name, category %>
							<ul class="feeds">
								<li>
									<% category.feeds.each do |feed| %>
										<%= link_to feed.title, feed %>&nbsp
									<% end %>
								</li>
							</ul>
						</li>
					<% end %>
				</ul>
			</div>
		</div>
	</div>
    <br />

	<%= render 'shared/entries' %>

<% end %>

app/views/entries/search.html.erb
<% content_for :main do %>
	<div align="center">
		<h1>Search results for "<%= @word %>"</h1>
		<%= link_to 'Entries', entries_path %>
		<br />
	</div>
	<%= render 'shared/entries' %>

<% end %>

app/views/entries/show.html.erb
<% content_for :main do %>

  <p>
    <b>Title:</b>
    <%= @entry.title %>
  </p>
  <p>
    <b>Published:</b>
    <%= @entry.published_at %>
  </p>
  <p>
    <b>Url:</b>
    <%= link_to @entry.url, @entry.url, :target=>["_blank"] %>
  </p>
  <p>
    <b>Feed:</b>
    <%= @entry.feed.title %>, <%= @entry.feed.category.name %>
  </p>
  <p>
    <b>Summary:</b>
    <%= @entry.summary %>
  </p>

  <%= link_to 'Entries', entries_path %>

<% end %>

app/views/entries/toggle_summary.js.erb
// accordion for summary by ajax
$(".s_<%= @entry.id %>").slideToggle('slow');

// re-layout items so as to summary field 
$(function(){
	var container = $('#cont').masonry();
	setTimeout(function(){
		$(container).masonry({
			itemSelector : '.item',
			isAnimated: true,
			//isFitWidth: true,
			isRTL: false,
			gutterWidth: 0
		})
	},
		400
	);
});