config/routes.rb
Rails.application.routes.draw do

  resources :feeds do
    member do
      get 'fetch'
    end
    collection do
      get 'search'
      get 'fetch_all'
    end
  end

  resources :categories

  get 'clips/index'
  get 'clips/vis'
  get 'clips/create'
  delete 'clips/destroy'

  resources :entries do
    member do
      get 'toggle_summary'
    end
    collection do
      get 'search'
    end
  end

  root :to => 'entries#index'

end

app/models/clip.rb
class Clip < ActiveRecord::Base
  belongs_to :entry
end

app/controllers/clips_controller.rb
class ClipsController < ApplicationController

  before_action :set_clipped_entries, :except => [:create, :destroy]
  before_action :set_categories, :except => [:create, :destroy]
  
  def clip_params
    params.require(:clip).permit(:entry_id)
  end

  def index
  end

  def vis
    @results = Entry.word_count(@entries)
    gon.results = @results
  end

  # POST /clips
  # POST /clips.json
  def create
    @entry = Entry.find(params[:e_id])
    @entry.create_clip(:entry_id => params[:e_id]) unless Clip.where(:entry_id => params[:e_id]).exists?
  end

  # DELETE /clips/1
  # DELETE /clips/1.json
  def destroy
    @entry = Entry.find(params[:e_id])
    @clip = @entry.clip
    @clip.destroy
  end

  def set_clipped_entries
    clipped_entries_id = Clip.pluck(:entry_id)
    @entries = Entry.where(:id => clipped_entries_id).page(params[:page])    
  end

  def set_categories
    @categories = Category.order(:name)
  end

  
end

app/helpers/clips_helper.rb
module ClipsHelper
end

app/views/clips/create.js.erb
$(".clip_<%= @entry.id %>")
	.removeClass("unclipped").addClass("clipped")
	.find("a")
	//.removeAttr("href")
	.attr("href", "<%= clips_destroy_url %>?e_id=<%= @entry.id %>")
	.removeAttr("data-method")
	.data("method", "delete");

app/views/clips/destroy.js.erb
$(".clip_<%= @entry.id %>")
  .removeClass("clipped").addClass("unclipped")
  .find("a")
  //.removeAttr("href")
  .attr("href", "<%= clips_create_url %>?e_id=<%= @entry.id %>")
  .removeAttr("data-method")
  .data("method", "get")
;

app/views/clips/index.html.erb
<% content_for :main do %>
    <%= include_gon %>
    <%= javascript_include_tag "d3/d3.min.js" %>
    <%= javascript_include_tag "d3/d3.layout.cloud.js" %>

	<div align="center">
		<h1>Clipped Entries</h1>

		<%= link_to 'Visualization', :action => :vis %>

		<br />
	</div>
	<%= render 'shared/entries' %>

<% end %>

app/views/clips/vis.html.erb
<% content_for :main do %>
    <%= include_gon %>
    <%= javascript_include_tag "d3/d3.min.js" %>
    <%= javascript_include_tag "d3/d3.layout.cloud.js" %>
    <div align="center">

		<h1>#Vis clipped entries</h1>

		<%# link_to 'All Entries', entries_path %>
		<%# link_to 'Feeds', feeds_path %>
		<%# link_to 'Categories', categories_path %>

		<div id="barchart"></div>
		<div id="word_cloud"></div>
		<div><%# @results %></div>
	</div>

	<script type="text/javascript">
	bar_chart(30);
	//word_cloud(100);
	</script>

<% end %>