config/routes.rb
Rails.application.routes.draw do

  resources :feeds do
    member do
      get 'fetch'
    end
    collection do
      get 'search'
      get 'fetch_all'
    end
  end

  resources :categories

  get 'clips/index'
  get 'clips/vis'
  get 'clips/create'
  delete 'clips/destroy'

  resources :entries do
    member do
      get 'toggle_summary'
    end
    collection do
      get 'search'
    end
  end

  root :to => 'entries#index'

end

app/views/shared/_entries.html.erb
<%= javascript_include_tag "masonry.pkgd.min" %>
<%= javascript_include_tag "imagesloaded.pkgd.min" %>
<%= javascript_include_tag "jquery/jquery.infinitescroll.min" %>

<%# page_entries_info @entries %>

<div id="cont">
	<% @entries.each do |entry| %>
		
		<div class="item">
			
			<span class="published_at">
  				<a><%=  entry.published_at.to_s[0..9] %></a>
			</span>
			
			<div class="title">
				<%= link_to entry.url, :target => ["_blank"] do %>
					<span class="inner_title"><%= entry.title %></span>
				<% end %>
			</div>
			
			<div class="item_footer">
				<div class="summary s_<%= entry.id %>">
					<%= entry.summary.slice(0,100) %>
				</div>

				<span class="meta">
					<a class="feed_title">
						<%= link_to_unless_current (
													if entry.feed.category then 
													entry.feed.category.name
													else
													"" 
													end
													),
													entry.feed.category
						%>
						<a>|</a>
						<%= link_to_unless_current (
													if entry.feed.title.length > 20
													entry.feed.title.slice(0,20) + "..." 
													else
													entry.feed.title
													end
													),
													entry.feed 
						%> 
					</a>
				</span>

				<span class="icons">
					<%= link_to toggle_summary_entry_url(entry), :remote => true do -%><i class="fa fa-coffee opn_smry"></i><% end %>
					<% if entry.clip %>
						<span class="clip_<%= entry.id %> clipped">
							<%= link_to "#{clips_destroy_url}"+"?e_id=#{entry.id}", :method => :delete, :remote => true do %>
								<i class="fa fa-star fa-2x"></i>
							<% end %>
						</span>
					<% else %>
						<span class="clip_<%= entry.id %> unclipped">
							<%= link_to "#{clips_create_url}"+"?e_id=#{entry.id}", :remote => true do %>
								<i class="fa fa-star fa-2x"></i>
							<% end %>
						</span>
					<% end %>
				</span>


			</div>
		</div>
	<% end %>
</div>

<div id="loading-area">
	<%= paginate @entries, :remote => true %>
</div>

<div id="fade_and_follow">
	<p><a id="move_top">▲</a></p>
</div>